export const database = [
    {
        id:1,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL130",
        size:"8-38",
        desc:"Extra super light",
        price:420,
        img:'img/strings/exl130',
        show:true    
    },
    {
        id:2,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL120",
        size:"9-42",
        desc:"Super light gauge",
        price:420,
        img:'/img/strings/exl120',
        show:true    
    },
    {
        id:3,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL125",
        size:"9-46",
        desc:"Super lt top | reg btm",
        price:420,
        img:'/img/strings/exl125',
        show:true    
    },
    {
        id:4,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL110",
        size:"10-46",
        desc:"Regular light gauge",
        price:420,
        img:'/img/strings/exl110',
        show:true    
    },
    {
        id:5,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL110W(3 в обмотке)",
        size:"10-46",
        desc:"Regular light gauge",
        price:450,
        img:'/img/strings/exl110w',
        show:true    
    },
    {
        id:6,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL140",
        size:"10-52",
        desc:"Light top/Heavy Btm",
        price:450,
        img:'/img/strings/exl140',
        show:true    
    },
    {
        id:7,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL115",
        size:"11-49",
        desc:"Medium gauge",
        price:420,
        img:'/img/strings/exl115',
        show:true    
    },
    {
        id:8,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL116",
        size:"11-52",
        desc:"Med top/Heavy btm",
        price:450,
        img:'/img/strings/exl116',
        show:true    
    },
    {
        id:9,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL117",
        size:"11-56",
        desc:"Med top/X-heavy btm",
        price:450,
        img:'/img/strings/exl117',
        show:true    
    },
    {
        id:10,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL125",
        size:"12-54",
        desc:"Heavy gauge",
        price:450,
        img:'/img/strings/exl145',
        show:true    
    },
    {
        id:11,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL148",
        size:"12-60",
        desc:"Extra heavy gauge",
        price:450,
        img:'/img/strings/exl148',
        show:true    
    },
    {
        id:12,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL120-7",
        size:"9-52",
        desc:"Super light gauge",
        price:540,
        img:'/img/strings/exl120-7',
        show:true    
    },
    {
        id:13,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"D`Addario",
        name:"D`Addario NICKEL WOUND EXL110-7",
        size:"10-59",
        desc:"Regular light gauge",
        price:540,
        img:'/img/strings/exl110-7',
        show:true    
    },
    {
        id:14,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"Elixir",
        name:"Elixir NANOWEB",
        size:"9-42",
        desc:"Super Light",
        price:1100,
        img:'/img/strings/12002',
        show:true    
    },
    {
        id:15,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"Elixir",
        name:"Elixir NANOWEB",
        size:"10-46",
        desc:"Light",
        price:1100,
        img:'/img/strings/12052',
        show:true    
    },
    {
        id:16,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"Elixir",
        name:"Elixir NANOWEB",
        size:"11-49",
        desc:"Medium",
        price:1100,
        img:'/img/strings/12102',
        show:true    
    },
    {
        id:17,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"eguitar",
        brand:"Elixir",
        name:"Elixir NANOWEB",
        size:"12-68",
        desc:"Baritone",
        price:1100,
        img:'/img/strings/12302',
        show:true    
    },
    {
        id:18,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"bass",
        brand:"Ernie Ball",
        name:"Ernie Ball",
        size:"45-65-80-100",
        desc:"Nickel Wound Bass Super Slinky",
        price:1700,
        img:'/img/strings/2834',
        show:true    
    },
    {
        id:19,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"bass",
        brand:"Ernie Ball",
        name:"Ernie Ball",
        size:"50-70-85-105",
        desc:"Nickel Wound Bass Regular Slinky",
        price:1700,
        img:'/img/strings/2832',
        show:true    
    },
    {
        id:20,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"bass",
        brand:"Ernie Ball",
        name:"Ernie Ball",
        size:"55-75-90-110",
        desc:"Nickel Wound Bass Power Slinky",
        price:1700,
        img:'/img/strings/2831',
        show:true    
    },
    {
        id:21,
        type: "str",
        inCart:false,
        count:0,
        total:0,
        for:"bass",
        brand:"Ernie Ball",
        name:"Ernie Ball",
        size:"45-65-80-100-130",
        desc:"Nickel Bass Reguilar Slinky 5",
        price:2100,
        img:'/img/strings/2836',
        show:true    
    },
    {
        id:22,
        type: "cable",
        inCart:false,
        count:0,
        total:0,
        for:null,
        brand:"Dunlop",
        name:"DCIS10 MXR",
        size:"3 м.",
        desc:"DCIS10 MXR Кабель инструментальный, 3 м.",
        price:930,
        img:'/img/cables/DCIS10',
        show:true    
    },
    {
        id:23,
        type: "pick",
        inCart:false,
        count:0,
        total:0,
        for:null,
        brand:"Dunlop",
        name:"Dunlop Stubby Triangle",
        size:"1.5 / 2.0 / 3.0",
        desc:"Dunlop Stubby Triangle",
        price:50,
        img:'/img/pick/stubby',
        show:true    
    },
    {
        id:24,
        type: "bag",
        inCart:false,
        count:0,
        total:0,
        for:'eguitar',
        brand:"BAG&music",
        name:"BM1035 Casual Electro",
        size:"",
        desc:"Чехол для электрогитары ",
        price:3000,
        img:'/img/bag/1035',
        show:true    
    },
    {
        id:25,
        typ: "bag",
        inCart:false,
        count:0,
        total:0,
        for:'eguitar',
        brand:"BAG&music",
        name:"BM1030 Electro PRO",
        size:"",
        desc:"Чехол для электрогитары ",
        price:7100,
        img:'/img/bag/1030',
        show:true    
    },
    {
        id:26,
        typ: "bag",
        inCart:false,
        count:0,
        total:0,
        for:'aguitar',
        brand:"BAG&music",
        name:"BM1039 Casual Acoustic",
        size:"",
        desc:"Чехол для акустической гитары",
        price:3300,
        img:'/img/bag/1039',
        show:true    
    },
    {
        id:27,
        typ: "bag",
        inCart:false,
        count:0,
        total:0,
        for:'bass',
        brand:"BAG&music",
        name:"BM1040 Casual Bass",
        size:"",
        desc:"Чехол для бас-гитары, черный",
        price:3100,
        img:'/img/bag/1040',
        show:true    
    },
];

export const productDetail =   {
    id:13,
    type: "str",
    inCart:false,
    count:0,
    total:0,
    for:"eguitar",
    brand:"D`Addario",
    name:"D`Addario NICKEL WOUND EXL110-7",
    size:"10-59",
    desc:"Regular light gauge",
    price:540,
    img:'/img/strings/exl110-7'
}

